language: rust
sudo: false
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
script:
  - cargo build --features="blocking"
  - cargo test --features="blocking"
