/// List of domains for some known
/// URL shortening services.
pub(crate) static SERVICES: [&str; 46] = [
    "adf.ly",
    "atominik.com",
    "b.link",
    "bit.ly",
    "bit.do",
    "bn.gy",
    "buff.ly",
    "chollo.to",
    "cutt.ly",
    "fa.by",
    "fb.me",
    "flip.it",
    "fumacrom.com",
    "git.io",
    "goo.gl",
    "gns.io",
    "hmm.rs",
    "is.gd",
    "intamema.com",
    "iz4.short.gy",
    "j.gs",
    "kutt.it",
    "ldn.im",
    "nmc.sg",
    "nowlinks.net",
    "ow.ly",
    "q.gs",
    "rebrand.ly",
    "rlu.ru",
    "rotf.lol",
    "s.coop",
    "sh.st",
    "smu.sg",
    "snipr.com",
    "snipurl.com",
    "snurl.com",
    "split.to",
    "t.co",
    "tiny.cc",
    "tinyurl.com",
    "tiny.one",
    "tny.im",
    "tny.sh",
    "tr.im",
    "v.gd",
    "zpr.io",
];

/// Check and tell which URL Shortner Service is used
pub(crate) fn which_service(url: &str) -> Option<&'static str> {
    SERVICES.iter().find(|&x| url.contains(x)).copied()
}
